name: NCS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: nordicplayground/nrfconnect-sdk:v2.4-branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # 1. Gerekli araçları yüklüyoruz (pip, git, west)
          apt-get -y update
          apt-get -y install python3-pip git
          pip3 install -U west

          # BURADA DEĞİŞİKLİK YAPTIK:
          # 'west init', 'west update' komutlarını SİLDİK.
          # Çünkü Docker içinde SDK zaten hazır ve senin projende west.yml yok.

      - name: Build application
        run: |
          # Direkt build komutunu çalıştırıyoruz.
          # Docker içindeki SDK (ZEPHYR_BASE) otomatik algılanır.
          west build -b nrf52840dk_nrf52840 -p always